services:
    app:
        network_mode: "host"
        build:
            context: .
            shm_size: 2gb
        shm_size: 2gb

        container_name: gifscrapper
        command: /bin/bash
        ports:
            - "8080:8000"
        volumes:
            - .:/code
        stdin_open: true
        tty: true
        ulimits:
            nofile:
                soft: 32768
                hard: 32768
